// https://github.com/jenkinsci/kubernetes-plugin
podTemplate(
    name: "jenkins-slave",
    inheritFrom: "jenkins-slave-backend",
    containers: [
        containerTemplate(name: "docker", image: "docker", ttyEnabled: true, command: 'cat'),
        containerTemplate(name: "kubectl", image: "lachlanevenson/k8s-kubectl:v1.18.3", ttyEnabled: true, command: 'cat')
    ],
    volumes: [
        hostPathVolume(mountPath: "/var/run/docker.sock", hostPath: "/var/run/docker.sock")
    ]
) {
    node(POD_LABEL) {
        def now = java.time.LocalDateTime.now()
        def projectId = "user-service"

        // git
        def gitUrl = "https://github.com/eGovFramework/egovframe-msa-${projectId}.git"
        def gitCredentialsId = "egovframesupport"

        // docker
        def dockerhubCredentialsId = "2a0c4873-017e-4ebe-b2a5-26a5ee52e9b0"
        def dockerImage = "egovframe/msa-${projectId}"
        def dockerImageTag = "k8s"

        stage("git") {
            // git url:"${gitUrl}", branch: "main", credentialsId: "${gitCredentialsId}"
            checkout scm
        }

        stage("gradle") {
            sh "./gradlew wrap --gradle-version=7.3 --daemon"
            sh "./gradlew bootJar"
        }

        stage("docker") {
            container("docker") {
                withCredentials([usernamePassword(credentialsId: "${dockerhubCredentialsId}", passwordVariable: "password", usernameVariable: "username")]) {
                    sh "docker login -u $username -p $password"
                    sh "docker build -f ./k8s-paasta/Dockerfile -t ${dockerImage}:${dockerImageTag} ."
                    sh "docker push ${dockerImage}:${dockerImageTag}"
                }
            }
        }

        stage( "kubernetes" ) {
            container("kubectl") {
                sh "kubectl rollout restart deployment ${projectId}-deployment || kubectl apply -f ./k8s-paasta"
                sh "kubectl annotate deployment.v1.apps/${projectId}-deployment kubernetes.io/change-cause='The image was updated at ${now} by ${env.BUILD_TAG}.'"
            }
        }
    }
}