apiVersion: v1
kind: Service
metadata:
  namespace: paas-9259d4fb-5313-4c32-ac42-558f9c550794-caas
  name: user-service
  labels:
    env: production
    tier: backend
    app: user-service
spec:
  ports:
    - name: user-service-http
      port: 80
      targetPort: 80
  # - name: user-service-https
  #   port: 443
  #   targetPort: 443
  selector:
    env: production
    tier: backend
    app: user-service