apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkins
  name: user-service-deployment
  annotations:
    kubernetes.io/change-cause: "Initialized by manifest files."
  labels:
    env: production
    tier: backend
    app: user-service
spec:
  replicas: 1 # 자원이 부족해서 1개만..
  selector:
    matchLabels:
      env: production
      tier: backend
      app: user-service
  template:
    metadata:
      labels:
        env: production
        tier: backend
        app: user-service
    spec:
      containers:
        - name: user-service
          image: overpsssion/egovframe-msa-backend-user-service:k8s
          imagePullPolicy: Always
          #resources:
          #  requests:
          #    cpu: 500m
          #    memory: 512Mi
          #  limits:
          #    cpu: 800m
          #    memory: 1024Mi
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 36
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 80
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: EUREKA_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: EUREKA_URI
            - name: APIGATEWAY_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: APIGATEWAY_URI
            - name: SPRING_CLOUD_CONFIG_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: SPRING_CLOUD_CONFIG_URI
            - name: MYSQL_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: MYSQL_HOSTNAME
            - name: RABBITMQ_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: RABBITMQ_HOSTNAME
            - name: ZIPKIN_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: ZIPKIN_HOSTNAME
            - name: LOGSTASH_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: LOGSTASH_URL
          ports:
            - containerPort: 80